<?xml version="1.0" encoding="utf-8"?><Database Name="Webtintuc" Class="dbWebTinTucDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VE8D64L\SQLEXPRESS;Initial Catalog=Webtintuc;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebtintucConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Role" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Account_Comment" Member="Comments" ThisKey="ID" OtherKey="ID_Account" Type="Comment" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Sub_Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ID_Category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateSubmitted" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="Nvarchar(50)" CanBeNull="false" />
      <Association Name="New_Comment" Member="Comments" ThisKey="ID" OtherKey="ID_News" Type="Comment" />
      <Association Name="category_New" Member="category" ThisKey="ID_Category" OtherKey="ID" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Advertisement" Member="Advertisement_Banners">
    <Type Name="Advertisement_Banner">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="category_New" Member="News" ThisKey="ID" OtherKey="ID_Category" Type="New" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_News" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Account_Comment" Member="Account" ThisKey="ID_Account" OtherKey="ID" Type="Account" IsForeignKey="true" />
      <Association Name="New_Comment" Member="New" ThisKey="ID_News" OtherKey="ID" Type="New" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Advertisement_Product" Member="Advertisement_Products">
    <Type Name="Advertisement_Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(9,0)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Advertisement" Member="Advertisements">
    <Type Name="Advertisement">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ListNews" Method="ListNews">
    <ElementType Name="ListNewsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Sub_Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateSubmitted" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Roles" Method="Roles">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="RolesResult">
      <Column Name="role" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>